[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
nom = "7.1.2"
rayon = "1.6.1"
ringbuf = "0.3.2"
thiserror = "1.0.38"
